import React from "react";
import { Box, Container, Typography } from "@mui/material";

const sections = [
  {
    title: "1. Introduction",
    content: [
      `CodeRize Technologies Pvt. Ltd. (“us”, “we”, or “our”) operates https://coderize.in/ (hereinafter referred to as “Service”).`,
      `Our Privacy Policy governs your visit to https://coderize.in/, and explains how we collect, safeguard and disclose information that results from your use of our Service.`,
      `We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.`,
      `Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).`,
    ],
  },
  {
    title: "2. Definitions",
    content: [
      `SERVICE means the https://coderize.in/ website operated by CodeRize Technologies Pvt. Ltd..`,
      `PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).`,
      `USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).`,
      `COOKIES are small files stored on your device (computer or mobile device).`,
      `DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.`,
      `DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.`,
      `DATA SUBJECT is any living individual who is the subject of Personal Data.`,
      `THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.`,
    ],
  },
  {
    title: "3. Information Collection and Use",
    content: [
      `We collect several different types of information for various purposes to provide and improve our Service to you.`,
    ],
  },
  {
    title: "4. Types of Data Collected",
    content: [
      `Personal Data`,
      `While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:`,
      `1. Email address`,
      `2. First name and last name`,
      `3. Phone number`,
      `4. Address, Country, State, Province, ZIP/Postal code, City`,
      `5. Cookies and Usage Data`,
      `We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.`,
      `Usage Data`,
      `We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”).`,
      `This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.`,
      `When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.`,
      `Tracking Cookies Data`,
      `We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.`,
      `Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.`,
      `You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.`,
      `Examples of Cookies we use:`,
      `1. Session Cookies: We use Session Cookies to operate our Service.`,
      `2. Preference Cookies: We use Preference Cookies to remember your preferences and various settings.`,
      `3. Security Cookies: We use Security Cookies for security purposes.`,
      `4. Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.`,
      `Other Data`,
      `While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.`,
    ],
  },
  {
    title: "5. Use of Data",
    content: [
      `CodeRize Technologies Pvt. Ltd. uses the collected data for various purposes:`,
      `1. to provide and maintain our Service;`,
      `2. to notify you about changes to our Service;`,
      `3. to allow you to participate in interactive features of our Service when you choose to do so;`,
      `4. to provide customer support;`,
      `5. to gather analysis or valuable information so that we can improve our Service;`,
      `6. to monitor the usage of our Service;`,
      `7. to detect, prevent and address technical issues;`,
      `8. to fulfil any other purpose for which you provide it;`,
      `9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;`,
      `10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;`,
      `11. to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;`,
      `12. in any other way we may describe when you provide the information;`,
      `13. for any other purpose with your consent.`,
    ],
  },
  {
    title: "6. Retention of Data",
    content: [
      `We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.`,
      `We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.`,
    ],
  },
  {
    title: "7. Transfer of Data",
    content: [
      `Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.`,
      `If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.`,
      `Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.`,
      `CodeRize Technologies Pvt. Ltd. will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.`,
    ],
  },
  {
    title: "8. Disclosure of Data",
    content: [
      `We may disclose personal information that we collect, or you provide:`,
      `1. Disclosure for Law Enforcement.`,
      `Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.`,
      `2. Business Transaction.`,
      `If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.`,
      `3. Other cases. We may disclose your information also:`,
      `1. to our subsidiaries and affiliates;`,
      `2. to contractors, service providers, and other third parties we use to support our business;`,
      `3. to fulfill the purpose for which you provide it;`,
      `4. for the purpose of including your company’s logo on our website;`,
      `5. for any other purpose disclosed by us when you provide the information;`,
      `6. with your consent in any other cases;`,
      `7. if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.`,
    ],
  },
  {
    title: "9. Security of Data",
    content: [
      `The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.`,
    ],
  },
  {
    title: "10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)",
    content: [
      `Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of CodeRize Technologies Pvt. Ltd. and its licensors. Service is protected by copyright, trademark, and other laws of and foreign countries. Our trademarks may not be used in connection with any product or service without the prior written consent of CodeRize Technologies Pvt. Ltd..If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.`,
      `We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.`,
      `If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at support@coderize.in.`,
      `In certain circumstances, you have the following data protection rights:`,
      `1. the right to access, update or to delete the information we have on you;`,
      `2. the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;`,
      `3. the right to object. You have the right to object to our processing of your Personal Data;`,
      `4. the right of restriction. You have the right to request that we restrict the processing of your personal information;`,
      `5. the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;`,
      `6. the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;`,
      `Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.`,
      `You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).`,
    ],
  },
  {
    title: "11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)",
    content: [
      `CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy.`,
      `According to CalOPPA we agree to the following:`,
      `1. users can visit our site anonymously;`,
      `2. our Privacy Policy link includes the word “Privacy”, and can easily be found on the home page of our website;`,
      `3. users will be notified of any privacy policy changes on our Privacy Policy Page;`,
      `4. users are able to change their personal information by emailing us at support@coderize.in.`,
      `Our Policy on “Do Not Track” Signals:`,
      `We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.`,
      `You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.`,
    ],
  },
  {
    title: "12. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)",
    content: [
      `If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:`,
      `What personal information we have about you. If you make this request, we will return to you:`,
      `1. The categories of personal information we have collected about you.`,
      `2. The categories of sources from which we collect your personal information.`,
      `3. The business or commercial purpose for collecting or selling your personal information.`,
      `4. The categories of third parties with whom we share personal information.`,
      `5. The specific pieces of personal information we have collected about you.`,
      `6. A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.`,
      `7. A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.`,
      `Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.`,
      `2. To delete your personal information. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.`,
      `3. To stop selling your personal information. We don’t sell or rent your personal information to any third parties for any purpose. We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a “sale” under California law. You are the only owner of your Personal Data and can request disclosure or deletion at any time.`,
      `If you submit a request to stop selling your personal information, we will stop making such transfers.`,
      
    ],
  },
  {
    title: "13. Error Reporting and Feedback",
    content: [
      ``,
    ],
  },
  {
    title: "14. Links To Other Web Sites",
    content: [
      `Our Service may contain links to third party web sites or services that are not owned or controlled by CodeRize Technologies Pvt. Ltd..`,
      `CodeRize Technologies Pvt. Ltd. has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third party web sites or services. We do not warrant the offerings of any of these entities/individuals or their websites.`,
      `For example, the outlined Terms of Use have been created using PolicyMaker.io, a free web application for generating high-quality legal documents. PolicyMaker’s Terms and Conditions generator is an easy-to-use free tool for creating an excellent standard Terms of Service template for a website, blog, e-commerce store or app.`,
      `YOU ACKNOWLEDGE AND AGREE THAT COMPANY SHALL NOT BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY DAMAGE OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH USE OF OR RELIANCE ON ANY SUCH CONTENT, GOODS OR SERVICES AVAILABLE ON OR THROUGH ANY SUCH THIRD PARTY WEB SITES OR SERVICES.`,
      `WE STRONGLY ADVISE YOU TO READ THE TERMS OF SERVICE AND PRIVACY POLICIES OF ANY THIRD PARTY WEB SITES OR SERVICES THAT YOU VISIT.`,
    ],
  },
  {
    title: "15. Disclaimer Of Warranty",
    content: [
      `THESE SERVICES ARE PROVIDED BY COMPANY ON AN “AS IS” AND “AS AVAILABLE” BASIS. COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THEIR SERVICES, OR THE INFORMATION, CONTENT OR MATERIALS INCLUDED THEREIN. YOU EXPRESSLY AGREE THAT YOUR USE OF THESE SERVICES, THEIR CONTENT, AND ANY SERVICES OR ITEMS OBTAINED FROM US IS AT YOUR SOLE RISK.`,
      `NEITHER COMPANY NOR ANY PERSON ASSOCIATED WITH COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE SERVICES. WITHOUT LIMITING THE FOREGOING, NEITHER COMPANY NOR ANYONE ASSOCIATED WITH COMPANY REPRESENTS OR WARRANTS THAT THE SERVICES, THEIR CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT THE SERVICES OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT THE SERVICES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS.`,
      `COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE.`,
      `THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.`,
    ],
  },
  {
    title: "16. Limitation Of Liability",
    content: [
        `EXCEPT AS PROHIBITED BY LAW, YOU WILL HOLD US AND OUR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS HARMLESS FOR ANY INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGE, HOWEVER IT ARISES (INCLUDING ATTORNEYS’ FEES AND ALL RELATED COSTS AND EXPENSES OF LITIGATION AND ARBITRATION, OR AT TRIAL OR ON APPEAL, IF ANY, WHETHER OR NOT LITIGATION OR ARBITRATION IS INSTITUTED), WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE, OR OTHER TORTIOUS ACTION, OR ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, INCLUDING WITHOUT LIMITATION ANY CLAIM FOR PERSONAL INJURY OR PROPERTY DAMAGE, ARISING FROM THIS AGREEMENT AND ANY VIOLATION BY YOU OF ANY FEDERAL, STATE, OR LOCAL LAWS, STATUTES, RULES, OR REGULATIONS, EVEN IF COMPANY HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. EXCEPT AS PROHIBITED BY LAW, IF THERE IS LIABILITY FOUND ON THE PART OF COMPANY, IT WILL BE LIMITED TO THE AMOUNT PAID FOR THE PRODUCTS AND/OR SERVICES, AND UNDER NO CIRCUMSTANCES WILL THERE BE CONSEQUENTIAL OR PUNITIVE DAMAGES. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE PRIOR LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.`
    ],
  },
  {
    title: "17. Termination",
    content: [
      `We may terminate or suspend your account and bar access to Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of Terms.`,
      `If you wish to terminate your account, you may simply discontinue using Service.`,
      `All provisions of Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.`
    ],
  },
  {
    title: "18. Governing Law",
    content: [
      `These Terms shall be governed and construed in accordance with the laws of India, which governing law applies to agreement without regard to its conflict of law provisions`,
      `Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service and supersede and replace any prior agreements we might have had between us regarding Service.`
    ],
  },
  {
    title: "19. Changes To Service",
    content: [
      `We reserve the right to withdraw or amend our Service, and any service or material we provide via Service, in our sole discretion without notice. We will not be liable if for any reason all or any part of Service is unavailable at any time or for any period. From time to time, we may restrict access to some parts of Service, or the entire Service, to users, including registered users.`,
    ],
  },
  {
    title: "20. Amendments To Terms",
    content: [
      `We may amend Terms at any time by posting the amended terms on this site. It is your responsibility to review these Terms periodically.`,
      `Your continued use of the Platform following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page frequently so you are aware of any changes, as they are binding on you.`,
      `By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Service.`
    ],
  },
  {
    title: "21. Waiver And Severability",
    content: [
      `No waiver by Company of any term or condition set forth in Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of Company to assert a right or provision under Terms shall not constitute a waiver of such right or provision.`,
      `If any provision of Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of Terms will continue in full force and effect.`
    ],
  },
  {
    title: "22. Acknowledgement",
    content: [
      `BY USING SERVICE OR OTHER SERVICES PROVIDED BY US, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF SERVICE AND AGREE TO BE BOUND BY THEM.`,
    ],
  },
  {
    title: "23. Contact Us",
    content: [
      `Please send your feedback, comments, requests for technical support by email: support@coderize.in.`,
    ],
  },
];

export default function PrivacyPolicy() {
  return (
    <Box
      sx={{
        backgroundColor: "#f2f2f2",
        minHeight: "100vh",
        py: { xs: 6, md: 10 },
      }}
    >
      <Container maxWidth="lg">
        <Box
          sx={{
            width: { xs: "100%", md: "78%" },
            mx: "auto",
          }}
        >
          <Typography
            variant="h2"
            sx={{
              color: "#0b3558",
              fontWeight: 500,
              mb: 7,
              fontSize: {
                xs: "2.3rem",
                sm: "2.8rem",
                md: "3.3rem",
              },
            }}
          >
            Privacy & Policy
          </Typography>

          {sections.map((section, index) => (
            <Box key={index} sx={{ mb: 7 }}>
              <Typography
                variant="h4"
                sx={{
                  color: "#0b3558",
                  mb: 3,
                  fontWeight: 500,
                  fontSize: {
                    xs: "1.7rem",
                    md: "2rem",
                  },
                }}
              >
                {section.title}
              </Typography>

              {section.content.map((text, i) => (
                <Typography
                  key={i}
                  sx={{
                    color: "#333",
                    lineHeight: 1.9,
                    mb: 2,
                    fontSize: {
                      xs: "1rem",
                      md: "1.15rem",
                    },
                  }}
                >
                  {text}
                </Typography>
              ))}
            </Box>
          ))}
        </Box>
      </Container>
    </Box>
  );
}